# Generated by Django 5.2.3 on 2025-07-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
