# Generated by Django 5.2.3 on 2025-07-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_otp_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ('-id', 'id')},
        ),
    ]
