# Generated by Django 5.2.3 on 2025-07-06 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(choices=[('matrimony', 'Matrimony Services'), ('events', 'Events'), ('entertainment', 'Entertainment'), ('services', 'Services'), ('property', 'Property'), ('automotive', 'Cars & Transport'), ('items', 'Items for Sale'), ('jobs', 'Jobs'), ('shops', 'Shops'), ('lifestyle', 'Lifestyle & Social'), ('travel', 'Travel'), ('announcements', 'Announcements'), ('help', 'Help & Advice'), ('news', 'News'), ('wedding', 'Wedding Services')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(choices=[('quran_teacher', 'Quran Teacher'), ('islamic_qa', 'Islamic Q & A'), ('nikah_service', 'Nikah Service'), ('bridal_show', 'Bridal Show'), ('ladies_islamic_speech', 'Ladies Islamic Speech'), ('islamic_shop', 'Islamic Shop'), ('mosques', 'Mosques'), ('funeral_services', 'Funeral Services'), ('charity', 'Charity'), ('perfume_shop', 'Perfume Shop'), ('umrah_package', 'Umrah Package'), ('stage_play', 'Stage Play'), ('live_music', 'Live Music Performance'), ('dance_performance', 'Dance Performance'), ('dj_set', 'DJ Set'), ('comedy_show', 'Comedy Show'), ('fashion_show', 'Fashion Show'), ('film_screening', 'Film Screening'), ('art_exhibition', 'Art Exhibition'), ('spoken_word', 'Spoken Word / Poetry'), ('builder', 'Builder'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('carpet_cleaner', 'Carpet & Pipe Cleaner'), ('immigration_solicitor', 'Immigration Solicitors'), ('insurance_broker', 'Insurance Broker'), ('web_app_developer', 'Web or App Developer'), ('mobile_pc_repair', 'Mobile & PC Repair'), ('cleaner', 'Cleaner'), ('baby_sitter', 'Baby Sitters'), ('interior_designer', 'Interior Designers'), ('personal_shopper', 'Personal Shopper'), ('body_guard', 'Body Guard'), ('personal_trainer', 'Personal Trainer'), ('chef', 'Chef'), ('travel_agent', 'Travel Agent'), ('property_for_sale', 'Property for Sale'), ('property_for_rent', 'Property for Rent'), ('property_maintenance', 'Property Maintenance'), ('estate_agents', 'Estate Agents'), ('mortgage_brokers', 'Mortgage Brokers'), ('cars_for_sale', 'Cars for Sale'), ('cars_for_rent', 'Cars for Rent'), ('car_hire', 'Car Hire'), ('coach_hire', 'Coach Hire'), ('minibus_hire', 'Minibus Hire'), ('driving_instructor', 'Driving Instructor'), ('accident_claims', 'Accident Claims Management'), ('garage', 'Garage'), ('bikes_for_sale', 'Bikes for Sale'), ('bikes_for_rent', 'Bikes for Rent'), ('bike_hire', 'Bike Hire'), ('electronics', 'Electronics'), ('appliances', 'Appliances'), ('furniture', 'Furniture'), ('home_garden', 'Home & Garden'), ('health_beauty', 'Health & Beauty'), ('groceries', 'Groceries'), ('restaurants', 'Restaurants'), ('fashion', 'Fashion'), ('barbers', 'Barbers'), ('jewellery_shop', 'Jewellery Shop'), ('cleaner_jobs', 'Cleaner'), ('care_worker', 'Care Worker'), ('childcare', 'Childcare'), ('chef_jobs', 'Chef'), ('cook', 'Cook'), ('kitchen_porter', 'Kitchen Porter'), ('builder_jobs', 'Builder'), ('plumber_jobs', 'Plumber'), ('electrician_jobs', 'Electrician'), ('retail_staff', 'Retail Staff'), ('delivery_driver', 'Delivery Driver'), ('waiter', 'Waiter'), ('event_staff', 'Event Staff'), ('catering_staff', 'Catering Staff'), ('mechanic', 'Mechanic'), ('mot_tester', 'MOT Tester'), ('tyre_fitter', 'Tyre Fitter'), ('day_out', 'Day Out'), ('night_out', 'Night Out'), ('day_trips', 'Day Trips'), ('mens_dayout', "Men's Day Out"), ('ladies_dayout', 'Ladies Day Out'), ('girls_dayout', 'Girls Day Out'), ('boys_dayout', 'Boys Day Out'), ('mens_nightout', "Men's Night Out"), ('ladies_nightout', 'Ladies Night Out'), ('girls_nightout', 'Girls Night Out'), ('boys_nightout', 'Boys Night Out'), ('babes_dayout', 'Babes Day Out'), ('bangladesh', 'Bangladesh'), ('saudi_arabia', 'Saudi Arabia'), ('dubai', 'Dubai'), ('morocco', 'Morocco'), ('turkey', 'Turkey'), ('tunisia', 'Tunisia'), ('egypt', 'Egypt'), ('malaysia', 'Malaysia'), ('singapore', 'Singapore'), ('thailand', 'Thailand'), ('usa', 'USA'), ('canada', 'Canada'), ('switzerland', 'Switzerland'), ('last_district', 'Last District'), ('snow_donia', 'Snow Donia'), ('bournemouth_curdle_door', 'Bournemouth & Curdle Door'), ('brighton', 'Brighton'), ('margate', 'Margate'), ('thorpe_park', 'Thorpe Park'), ('chessington', 'Chessington'), ('alton_towers', 'Alton Towers'), ('blackpool', 'Blackpool'), ('manchester', 'Manchester'), ('liverpool', 'Liverpool'), ('glasgow', 'Glasgow'), ('edinburgh', 'Edinburgh'), ('wedding_event', 'Wedding Event'), ('wedding_catering', 'Wedding Catering'), ('photography', 'Photography'), ('wedding_function_hall', 'Wedding Function Hall'), ('flower_decoration', 'Flower Decoration'), ('bridal_makeup', 'Bridal Makeup'), ('groom_makeup', 'Groom Makeup')], max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ads.category')),
            ],
            options={
                'ordering': ['order', 'display_name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('location', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('sold', 'Sold')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('publik_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ads.ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ad')},
            },
        ),
    ]
