# Generated by Django 5.2.3 on 2025-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
