# Generated by Django 5.2.3 on 2025-07-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_is_expired_ad_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('sold', 'Sold')], default='active', max_length=20),
        ),
    ]
