# Generated by Django 5.2.3 on 2025-07-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='pending_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('sold', 'Sold')], default='pending', max_length=20),
        ),
    ]
