# Generated by Django 5.2.3 on 2025-07-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_ad_id_alter_category_id_alter_favoritead_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('sold', 'Sold')], default='active', max_length=20),
        ),
    ]
