# Generated by Django 5.2.3 on 2025-07-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
