# Generated by Django 5.2.3 on 2025-07-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0004_alter_bookmark_id_alter_connectionrequest_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ('-id', 'id')},
        ),
        migrations.AlterModelOptions(
            name='matrimonyprofile',
            options={'ordering': ('-id', 'id')},
        ),
        migrations.AlterModelOptions(
            name='matrimonyprofilepicture',
            options={'ordering': ('-id', 'id')},
        ),
        migrations.AlterModelOptions(
            name='partnerpreference',
            options={'ordering': ('-id', 'id')},
        ),
    ]
